name: dev

on:
  push:
    branches:
      - dev

jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Trigger Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.TARGET_REPO_OWNER }}/${{ secrets.TARGET_REPO_NAME }}/dispatches \
            -d '{
              "event_type":"trigger-workflow",
              "client_payload":{
                "unit":false,
                "integration":true,
                "branch":"${{ github.ref_name }}",
                "env":"dev"}
                }'
